[package]
name = "geohash-py"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "geohash_py"
crate-type = ["cdylib"]

[dependencies]
geohash = "0.13.1"
pyo3 = "0.20.0"
log = "0.4.21"
